In [31]:
import pandas as pd
import numpy as np

In [32]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\Fernando Acácio\OneDrive\Área de Trabalho\Entra21\Python\machine_learning\Aula 02\Aula02_Limpeza_Preparacao_Dados\datasets\sujos\clientes_sujo.csv"
)

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

df

,ID,Nome,Idade,Cidade,Renda,Visitas_Site,Compras_Anteriores,Comprou
0,1,Cliente 1,48,Joinville,14687.0,12,13,Sim
1,2,Cliente 2,36,Joinville,5907.0,0,1,Não
2,3,Cliente 3,59,Pomerode,NaN,14,25,Sim
3,4,Cliente 4,49,Timbó,7397.0,6,8,Sim
4,5,Cliente 5,49,Indaial,9145.0,16,24,Sim
5,6,Cliente 6,69,blumenau,8614.0,17,21,Sim
6,7,Cliente 7,71,Blumenau,6252.0,10,14,Sim
7,8,Cliente 8,46,BLUMENAU,12794.0,22,25,Sim
8,9,Cliente 9,34,Indaial,8920.0,5,30,Sim
9,10,Cliente 10,71,Blumenau,13427.0,15,30,Sim
10,11,Cliente 11,-2,Blumenau,5865.0,15,11,Sim
11,12,Cliente 12,30,Indaial,13747.0,13,4,Sim
12,13,Cliente 13,18,Pomerode,3010.0,0,14,Sim
13,14,Cliente 14,52,Joinville,2860.0,19,25,Sim
14,15,Cliente 15,33,Pomerode,-1200.0,19,1,Não
15,16,Cliente 16,35,Gaspar,12452.0,24,20,Sim
16,17,Cliente 17,27,Pomerode,1584.0,10,21,Sim
17,18,Cliente 18,54,Timbó,14107.0,15,22,Sim
18,19,Cliente 19,26,Pomerode,10442.0,7,dez,Sim
19,20,Cliente 20,26,Gaspar,11299.0,22,16,Sim
20,21,Cliente 21,23,Joinville,8344.0,21,5,Sim
21,22,Cliente 22,68,Pomerode,14319.0,18,9,Sim
22,23,Cliente 23,44,Pomerode,7896.0,25,4,Sim
23,24,Cliente 24,69,Blumenau,4722.0,12,0,Sim
24,25,Cliente 25,42,Gaspar,2703.0,1,26,Sim
25,26,Cliente 26,59,Blumenau,7290.0,24,30,Sim
26,27,Cliente 27,19,Timbó,9862.0,15,10,Sim
27,28,Cliente 28,37,Blumenau,8875.0,10,29,Sim
28,29,Cliente 29,49,Joinville,9144.0,18,19,Sim
29,30,Cliente 30,27,Indaial,11187.0,16,6,Sim
30,31,Cliente 31,57,Joinville,7011.0,14,19,Sim
31,32,Cliente 32,61,Indaial,13147.0,2,17,Sim
32,33,Cliente 33,20,Joinville,4702.0,20,29,Sim
33,34,Cliente 34,20,Blumenau,12120.0,17,29,Sim
34,35,Cliente 35,46,Indaial,13865.0,20,6,Sim
35,36,Cliente 36,63,Timbó,12618.0,0,4,Não
36,37,Cliente 37,51,Pomerode,5083.0,25,28,Sim
37,38,Cliente 38,26,Joinville,4127.0,21,27,Sim
38,39,Cliente 39,42,Indaial,5969.0,13,17,Sim
39,40,Cliente 40,23,Gaspar,7778.0,9,5,Sim
40,41,Cliente 41,29,Indaial,5816.0,14,15,Sim
41,42,Cliente 42,36,Pomerode,9162.0,5,10,Sim
42,43,Cliente 43,48,Pomerode,8784.0,3,16,Sim
43,44,Cliente 44,68,Joinville,5986.0,3,27,Sim
44,45,Cliente 45,32,Indaial,1580.0,2,28,Sim
45,46,Cliente 46,59,Timbó,6913.0,13,17,Sim
46,47,Cliente 47,29,Joinville,1945.0,11,27,Sim
47,48,Cliente 48,40,Pomerode,10707.0,21,18,Sim
48,49,Cliente 49,31,Gaspar,3297.0,19,22,Sim
49,50,Cliente 50,53,Joinville,13808.0,18,23,Sim
50,7,Cliente 7,71,Blumenau,6252.0,10,14,Sim

In [51]:
dfCliente = df
print(dfCliente.dtypes)

ID                      int64
Nome                      str
Idade                   int64
Cidade                    str
Renda                 float64
Visitas_Site            int64
Compras_Anteriores        str
Comprou                   str
dtype: object

In [ ]:

print(dfCliente.shape)

(51, 8)

In [34]:
dfCliente[dfCliente.duplicated()]

,ID,Nome,Idade,Cidade,Renda,Visitas_Site,Compras_Anteriores,Comprou
50,7,Cliente 7,71,Blumenau,6252.0,10,14,Sim

In [35]:
dfCliente.duplicated().sum()

np.int64(1)

In [36]:
dfCliente[dfCliente.duplicated(keep=False)]

,ID,Nome,Idade,Cidade,Renda,Visitas_Site,Compras_Anteriores,Comprou
6,7,Cliente 7,71,Blumenau,6252.0,10,14,Sim
50,7,Cliente 7,71,Blumenau,6252.0,10,14,Sim

In [37]:
dfCliente = dfCliente.drop_duplicates()

In [38]:
dfCliente.style.hide(axis="index")

In [41]:
dfCliente[dfCliente.isna().any(axis=1)]

,ID,Nome,Idade,Cidade,Renda,Visitas_Site,Compras_Anteriores,Comprou
2,3,Cliente 3,59,Pomerode,NaN,14,25,Sim

In [45]:
dfCliente["Renda"].mean()

np.float64(8164.673469387755)

In [46]:
dfCliente["Renda"] = dfCliente["Renda"].fillna(dfCliente["Renda"].median())

In [47]:
dfCliente

,ID,Nome,Idade,Cidade,Renda,Visitas_Site,Compras_Anteriores,Comprou
0,1,Cliente 1,48,Joinville,14687.0,12,13,Sim
1,2,Cliente 2,36,Joinville,5907.0,0,1,Não
2,3,Cliente 3,59,Pomerode,8344.0,14,25,Sim
3,4,Cliente 4,49,Timbó,7397.0,6,8,Sim
4,5,Cliente 5,49,Indaial,9145.0,16,24,Sim
5,6,Cliente 6,69,blumenau,8614.0,17,21,Sim
6,7,Cliente 7,71,Blumenau,6252.0,10,14,Sim
7,8,Cliente 8,46,BLUMENAU,12794.0,22,25,Sim
8,9,Cliente 9,34,Indaial,8920.0,5,30,Sim
9,10,Cliente 10,71,Blumenau,13427.0,15,30,Sim
10,11,Cliente 11,-2,Blumenau,5865.0,15,11,Sim
11,12,Cliente 12,30,Indaial,13747.0,13,4,Sim
12,13,Cliente 13,18,Pomerode,3010.0,0,14,Sim
13,14,Cliente 14,52,Joinville,2860.0,19,25,Sim
14,15,Cliente 15,33,Pomerode,-1200.0,19,1,Não
15,16,Cliente 16,35,Gaspar,12452.0,24,20,Sim
16,17,Cliente 17,27,Pomerode,1584.0,10,21,Sim
17,18,Cliente 18,54,Timbó,14107.0,15,22,Sim
18,19,Cliente 19,26,Pomerode,10442.0,7,dez,Sim
19,20,Cliente 20,26,Gaspar,11299.0,22,16,Sim
20,21,Cliente 21,23,Joinville,8344.0,21,5,Sim
21,22,Cliente 22,68,Pomerode,14319.0,18,9,Sim
22,23,Cliente 23,44,Pomerode,7896.0,25,4,Sim
23,24,Cliente 24,69,Blumenau,4722.0,12,0,Sim
24,25,Cliente 25,42,Gaspar,2703.0,1,26,Sim
25,26,Cliente 26,59,Blumenau,7290.0,24,30,Sim
26,27,Cliente 27,19,Timbó,9862.0,15,10,Sim
27,28,Cliente 28,37,Blumenau,8875.0,10,29,Sim
28,29,Cliente 29,49,Joinville,9144.0,18,19,Sim
29,30,Cliente 30,27,Indaial,11187.0,16,6,Sim
30,31,Cliente 31,57,Joinville,7011.0,14,19,Sim
31,32,Cliente 32,61,Indaial,13147.0,2,17,Sim
32,33,Cliente 33,20,Joinville,4702.0,20,29,Sim
33,34,Cliente 34,20,Blumenau,12120.0,17,29,Sim
34,35,Cliente 35,46,Indaial,13865.0,20,6,Sim
35,36,Cliente 36,63,Timbó,12618.0,0,4,Não
36,37,Cliente 37,51,Pomerode,5083.0,25,28,Sim
37,38,Cliente 38,26,Joinville,4127.0,21,27,Sim
38,39,Cliente 39,42,Indaial,5969.0,13,17,Sim
39,40,Cliente 40,23,Gaspar,7778.0,9,5,Sim
40,41,Cliente 41,29,Indaial,5816.0,14,15,Sim
41,42,Cliente 42,36,Pomerode,9162.0,5,10,Sim
42,43,Cliente 43,48,Pomerode,8784.0,3,16,Sim
43,44,Cliente 44,68,Joinville,5986.0,3,27,Sim
44,45,Cliente 45,32,Indaial,1580.0,2,28,Sim
45,46,Cliente 46,59,Timbó,6913.0,13,17,Sim
46,47,Cliente 47,29,Joinville,1945.0,11,27,Sim
47,48,Cliente 48,40,Pomerode,10707.0,21,18,Sim
48,49,Cliente 49,31,Gaspar,3297.0,19,22,Sim
49,50,Cliente 50,53,Joinville,13808.0,18,23,Sim

In [48]:
dfCliente[dfCliente.isna().any(axis=1)]

Empty DataFrame
Columns: [ID, Nome, Idade, Cidade, Renda, Visitas_Site, Compras_Anteriores, Comprou]
Index: []

In [52]:
dfCliente["Cidade"] = dfCliente["Cidade"].str.strip().str.title()
dfCliente

,ID,Nome,Idade,Cidade,Renda,Visitas_Site,Compras_Anteriores,Comprou
0,1,Cliente 1,48,Joinville,14687.0,12,13,Sim
1,2,Cliente 2,36,Joinville,5907.0,0,1,Não
2,3,Cliente 3,59,Pomerode,NaN,14,25,Sim
3,4,Cliente 4,49,Timbó,7397.0,6,8,Sim
4,5,Cliente 5,49,Indaial,9145.0,16,24,Sim
5,6,Cliente 6,69,Blumenau,8614.0,17,21,Sim
6,7,Cliente 7,71,Blumenau,6252.0,10,14,Sim
7,8,Cliente 8,46,Blumenau,12794.0,22,25,Sim
8,9,Cliente 9,34,Indaial,8920.0,5,30,Sim
9,10,Cliente 10,71,Blumenau,13427.0,15,30,Sim
10,11,Cliente 11,-2,Blumenau,5865.0,15,11,Sim
11,12,Cliente 12,30,Indaial,13747.0,13,4,Sim
12,13,Cliente 13,18,Pomerode,3010.0,0,14,Sim
13,14,Cliente 14,52,Joinville,2860.0,19,25,Sim
14,15,Cliente 15,33,Pomerode,-1200.0,19,1,Não
15,16,Cliente 16,35,Gaspar,12452.0,24,20,Sim
16,17,Cliente 17,27,Pomerode,1584.0,10,21,Sim
17,18,Cliente 18,54,Timbó,14107.0,15,22,Sim
18,19,Cliente 19,26,Pomerode,10442.0,7,dez,Sim
19,20,Cliente 20,26,Gaspar,11299.0,22,16,Sim
20,21,Cliente 21,23,Joinville,8344.0,21,5,Sim
21,22,Cliente 22,68,Pomerode,14319.0,18,9,Sim
22,23,Cliente 23,44,Pomerode,7896.0,25,4,Sim
23,24,Cliente 24,69,Blumenau,4722.0,12,0,Sim
24,25,Cliente 25,42,Gaspar,2703.0,1,26,Sim
25,26,Cliente 26,59,Blumenau,7290.0,24,30,Sim
26,27,Cliente 27,19,Timbó,9862.0,15,10,Sim
27,28,Cliente 28,37,Blumenau,8875.0,10,29,Sim
28,29,Cliente 29,49,Joinville,9144.0,18,19,Sim
29,30,Cliente 30,27,Indaial,11187.0,16,6,Sim
30,31,Cliente 31,57,Joinville,7011.0,14,19,Sim
31,32,Cliente 32,61,Indaial,13147.0,2,17,Sim
32,33,Cliente 33,20,Joinville,4702.0,20,29,Sim
33,34,Cliente 34,20,Blumenau,12120.0,17,29,Sim
34,35,Cliente 35,46,Indaial,13865.0,20,6,Sim
35,36,Cliente 36,63,Timbó,12618.0,0,4,Não
36,37,Cliente 37,51,Pomerode,5083.0,25,28,Sim
37,38,Cliente 38,26,Joinville,4127.0,21,27,Sim
38,39,Cliente 39,42,Indaial,5969.0,13,17,Sim
39,40,Cliente 40,23,Gaspar,7778.0,9,5,Sim
40,41,Cliente 41,29,Indaial,5816.0,14,15,Sim
41,42,Cliente 42,36,Pomerode,9162.0,5,10,Sim
42,43,Cliente 43,48,Pomerode,8784.0,3,16,Sim
43,44,Cliente 44,68,Joinville,5986.0,3,27,Sim
44,45,Cliente 45,32,Indaial,1580.0,2,28,Sim
45,46,Cliente 46,59,Timbó,6913.0,13,17,Sim
46,47,Cliente 47,29,Joinville,1945.0,11,27,Sim
47,48,Cliente 48,40,Pomerode,10707.0,21,18,Sim
48,49,Cliente 49,31,Gaspar,3297.0,19,22,Sim
49,50,Cliente 50,53,Joinville,13808.0,18,23,Sim
50,7,Cliente 7,71,Blumenau,6252.0,10,14,Sim

In [53]:
mediana = dfCliente.loc[dfCliente["Idade"] >= 0, "Idade"].median()
dfCliente.loc[dfCliente["Idade"] == -2, "Idade"] = mediana

dfCliente

,ID,Nome,Idade,Cidade,Renda,Visitas_Site,Compras_Anteriores,Comprou
0,1,Cliente 1,48,Joinville,14687.0,12,13,Sim
1,2,Cliente 2,36,Joinville,5907.0,0,1,Não
2,3,Cliente 3,59,Pomerode,NaN,14,25,Sim
3,4,Cliente 4,49,Timbó,7397.0,6,8,Sim
4,5,Cliente 5,49,Indaial,9145.0,16,24,Sim
5,6,Cliente 6,69,Blumenau,8614.0,17,21,Sim
6,7,Cliente 7,71,Blumenau,6252.0,10,14,Sim
7,8,Cliente 8,46,Blumenau,12794.0,22,25,Sim
8,9,Cliente 9,34,Indaial,8920.0,5,30,Sim
9,10,Cliente 10,71,Blumenau,13427.0,15,30,Sim
10,11,Cliente 11,43,Blumenau,5865.0,15,11,Sim
11,12,Cliente 12,30,Indaial,13747.0,13,4,Sim
12,13,Cliente 13,18,Pomerode,3010.0,0,14,Sim
13,14,Cliente 14,52,Joinville,2860.0,19,25,Sim
14,15,Cliente 15,33,Pomerode,-1200.0,19,1,Não
15,16,Cliente 16,35,Gaspar,12452.0,24,20,Sim
16,17,Cliente 17,27,Pomerode,1584.0,10,21,Sim
17,18,Cliente 18,54,Timbó,14107.0,15,22,Sim
18,19,Cliente 19,26,Pomerode,10442.0,7,dez,Sim
19,20,Cliente 20,26,Gaspar,11299.0,22,16,Sim
20,21,Cliente 21,23,Joinville,8344.0,21,5,Sim
21,22,Cliente 22,68,Pomerode,14319.0,18,9,Sim
22,23,Cliente 23,44,Pomerode,7896.0,25,4,Sim
23,24,Cliente 24,69,Blumenau,4722.0,12,0,Sim
24,25,Cliente 25,42,Gaspar,2703.0,1,26,Sim
25,26,Cliente 26,59,Blumenau,7290.0,24,30,Sim
26,27,Cliente 27,19,Timbó,9862.0,15,10,Sim
27,28,Cliente 28,37,Blumenau,8875.0,10,29,Sim
28,29,Cliente 29,49,Joinville,9144.0,18,19,Sim
29,30,Cliente 30,27,Indaial,11187.0,16,6,Sim
30,31,Cliente 31,57,Joinville,7011.0,14,19,Sim
31,32,Cliente 32,61,Indaial,13147.0,2,17,Sim
32,33,Cliente 33,20,Joinville,4702.0,20,29,Sim
33,34,Cliente 34,20,Blumenau,12120.0,17,29,Sim
34,35,Cliente 35,46,Indaial,13865.0,20,6,Sim
35,36,Cliente 36,63,Timbó,12618.0,0,4,Não
36,37,Cliente 37,51,Pomerode,5083.0,25,28,Sim
37,38,Cliente 38,26,Joinville,4127.0,21,27,Sim
38,39,Cliente 39,42,Indaial,5969.0,13,17,Sim
39,40,Cliente 40,23,Gaspar,7778.0,9,5,Sim
40,41,Cliente 41,29,Indaial,5816.0,14,15,Sim
41,42,Cliente 42,36,Pomerode,9162.0,5,10,Sim
42,43,Cliente 43,48,Pomerode,8784.0,3,16,Sim
43,44,Cliente 44,68,Joinville,5986.0,3,27,Sim
44,45,Cliente 45,32,Indaial,1580.0,2,28,Sim
45,46,Cliente 46,59,Timbó,6913.0,13,17,Sim
46,47,Cliente 47,29,Joinville,1945.0,11,27,Sim
47,48,Cliente 48,40,Pomerode,10707.0,21,18,Sim
48,49,Cliente 49,31,Gaspar,3297.0,19,22,Sim
49,50,Cliente 50,53,Joinville,13808.0,18,23,Sim
50,7,Cliente 7,71,Blumenau,6252.0,10,14,Sim

In [60]:
dfCliente["Idade"] = dfCliente["Idade"].astype(float)
print(dfCliente.dtypes)

ID                      int64
Nome                      str
Idade                 float64
Cidade                    str
Renda                 float64
Visitas_Site            int64
Compras_Anteriores        str
Comprou                   str
dtype: object

In [63]:
dfCliente["Idade"] = dfCliente["Idade"].astype(int)
print(dfCliente.dtypes)

ID                      int64
Nome                      str
Idade                   int64
Cidade                    str
Renda                 float64
Visitas_Site            int64
Compras_Anteriores        str
Comprou                   str
dtype: object